- src/lib/components/ChatMessage.svelte
I felt like I has having to "wait around" for tooltip to load. This value feels like a good mix of quickness without accidentally triggering. This is subjective so I understand if you want to keep current value.
> feat: show datetime tooltip faster.

- deno.lock
- package.json
- src/lib/components/ThreadRow.svelte
- src/routes/(app)/+layout.svelte
- src/routes/(app)/dm/[did]/+page.svelte
Implements new UI for the thread tab, where each are a row that on click will add a `?thread=<ulid>` search parameter to the DM URL. The tab will then render all the messages in the thread.
Each row has the title, the latest message's time in the thread, number of the messages in the thread, and a delete button that opens a dialog to confirm deletion.
Closes #40 
Closes #33 
https://github.com/user-attachments/assets/0299c487-6748-4e98-bc3b-dc42d0439410
> feat: threads interface v1

- src/lib/components/ChatArea.svelte
- src/lib/components/ChatMessage.svelte
- src/lib/profile.svelte.ts
- src/routes/(app)/dm/[did]/+page.svelte
Implements replying UX flow, where users can select a message to "reply to", which sets it as part of the input, indicated by a preview above the text box. They can deselect it or select another message. Messages that are replying to another will have a banner showing the other above it. Clicking the banner will scroll the user to that position.
> feat: reply UX v1

- src/lib/components/ChatMessage.svelte
Creates a new local `timestamp` snippet for `ChatMessage` that calculates whether the timestamp is from today and will either say "Today, <time>" or "<date>, <time>"
Closes #53 
**Today Example**
**Previous days examples**
> style: better time format

- src/routes/(app)/space/[space]/+layout.svelte
Add a `currentChannelId` state variable in the space's layout and bind all channel toggle groups to that one variable.
Closes #54
> fix: only select one space channel

- deno.lock
- package.json
- src/lib/components/ChatInput.svelte
- src/routes/(app)/+layout.svelte
Implement an `$effect` in `ChatInput` that destroys and updates the existing tiptap editor instance when extension changes. 
Closes #87
> fix: update tiptap editor on extension change

- deno.lock
- package.json
- src/app.css
- src/lib/components/ChatArea.svelte
- src/lib/components/ChatMessage.svelte
- src/lib/components/Dialog.svelte
- src/lib/schemas/types.ts
- src/lib/utils.ts
- src/routes/(app)/space/[space]/+layout.svelte
- src/routes/(app)/space/[space]/[channel]/+page.svelte
- src/routes/(app)/space/[space]/thread/[thread]/+page.svelte
- src/routes/(app)/space/[space]/thread/[ulid]/+page.svelte
Implements a new Threads UX where users now "move" messages from a channel (or thread)'s timeline to a new 'Thread' timeline available Space-wide.
- Threads now live under the `/space/[space]/thread/[thread]` URL, not attached to a specific channel 
- Threads now have a `relatedChannel` field to know it's origin, threads made from existing threads will have the same `relatedChannel`
- Users can navigate to threads using the sidebar alongside the channel selector, alongside the existing Chat/Threads tabs
- Update the sidebar on URL change, highlighting the current channel/thread
- Implements a new timeline event type called `Announcements` which shows a change to the Space; this PR implements the `threadCreated` and `messageMoved` announcement types
- Changes and refactor to `ChatMessage` …
> feat: ejected threads

- src/lib/global.svelte.ts
This fixes issues with old databases from previous versions of roomy if a user has used an older version.
> fix: add unique version to Roomy IndexedDB database name.

- src/lib/components/ChatArea.svelte
Still needs work, but it's better than nothing right now.
Future improvements include:
- Not scrolling to the bottom when somebody chats if you are scrolled back in history
- Remembering your last scroll position in different channels instead of just scrolling to the bottom every time you click to a new channel ( but also only doing that if you are scrolled high enough in history ).
> fix: scroll to end of channel when chatting.

- src/lib/components/TimelineView.svelte
- src/lib/utils.svelte.ts
There was a bug in the sidebar that was linking to threads using the channel URL scheme so things were showing up as channel settings instead of thread settings.
> fix: fix thread links in sidebar linking to threads as channels.

- src/routes/(app)/[[spaceIndicator=dash]]/[space=space]/+layout.svelte
We might have a more useful index page later, and we will want to remember the last channel you were in for each space, but this is an easy temporary fix.
> feat: automatically navigate to the first channel in a space when navigating to the space.

- src/lib/components/Dialog.svelte
- src/lib/stores/dialog.ts
- src/lib/user.svelte.ts
- src/routes/(app)/+layout.svelte
- src/routes/(app)/home/+page.svelte
Turns out we weren't correctly awaiting out atproto call in our user.init() function. This now returns correctly after the call finishes which allows us to remove an effect 🎉 (always a win!). Looking at the user object, I also cleaned up the cases where we lose the user.session to keep the user in a cleaner state.
_Just in case they miss the auto-dialog (which now works more consistently)_
_Still room for improvement here. A loading state probably makes sense._
> Fix: user session out-of-date

- src/lib/actions/useFocusOnRender.svelte.ts
- src/lib/components/Dialog.svelte
- src/lib/components/WikiEditor.svelte
In between mobile updates, I got mad at the auto focus not working correctly so I decided to fix it. There are a couple of general component fixes in this PR. Who was the one that told me Svelte was so nice again? 👀 I feel so sloooow.
> [!CAUTION]
> We're still leaking some data here somehow. We should only be returning data that hasn't been deleted from the server rather than filtering it on the client. 
https://github.com/user-attachments/assets/7aa57260-7e57-4a02-ad35-16165663493d
> Fix: adds ability to auto-focus elements and improves wiki deletion

- src/hooks.client.ts
- src/lib/components/ThemeSelector.svelte
We already store the theme in local storage, so I don't think the cookie is necessary. The default was also being set to something different, then overridden in another place.
> chore: remove theme storage in cookie

- scripts/netlify_build.sh
The previous commit adding Netlify redirects for Posthog apparently overwrote a default redirect rule that Netlify needs to apply to properly route SPAs. This adds an SPA routing rule.
> chore: fix netlify SPA redirect broken after adding Posthog redirect.

- scripts/netlify_build.sh
- static/_redirects
Apparently sveltekit's Netlify adapter automatically appends to the _redirects file at build time, so we have to put our custom redirects in the static folder so that they don't overwrite the sveltekit redirects.
> chore: put the netlify redirects in static folder instead of in build script.

- src/routes/(app)/+page.server.ts
- src/routes/(app)/+page.svelte
Because we redirect users to home immediately, Firefox (for me) would render the page twice and cause a gross-looking browser style *hiccup*. This fixes it. The page should load quicker now for users on browsers outside of chrome which seemed to handle this correctly by default.
> fix: adds correct redirect for initial load from server

- src/lib/urlUtils.ts
I believe this was broken by adding linkify-it in #150. Now we parse out the HTML that isn't plain text and leave it untouched.
> fix: display mentions in chat as clickable links

- .github/workflows/release-tauri.yml
Github workflow to trigger building and publishing Tauri distributions for desktop and android platforms. Current trigger requires a tagged release with a matching version to what is in src-tauri/tauri.config.json.
> build: tauri publish workflow

- src/app.css
- src/lib/components/TimelineToolbar.svelte
- src/routes/(app)/+layout.svelte
Unrelated tweaks:
- removed hover animation on some buttons
- cursor now changes to pointer by default on all buttons (we were doing this manually on each one before lol)
Shot 1:
- replaced invite button with new icon
- added explainer copy to `Create thread` popup
- added close button to popup
Shot 2:
- added success toast on invite button click - fixes: #173 
| Shot 1 | Shot 2 |
|--------|--------|
| ![Screenshot 2025-05-02 012749](https://github.com/user-attachments/assets/d579993d-e9bc-4237-a7a5-2df3ffdfb543) | ![Screenshot 2025-05-02 012757](https://github.com/user-attachments/assets/524d194d-1c15-437a-a2bb-3731ea076b36) |
> fix: improvements to invite and thread toolbar

- src/app.css
- src/lib/components/ChatMessage.svelte
- src/lib/components/SuggestionSelect.svelte
- src/lib/components/TimelineView.svelte
- tailwind.config.ts
closes: #109
This one should be a nice little clean-up of several styles that were still hard-coded and didn't adapt with the theme. I've also made some subtle, but much needed changes to our message padding.
Each message is now given just a bit more space to breathe while still keeping messages grouped. The hover effects and padding have been adjusted as well. Everything should just feel less **claustrophobic** overall. Oh, and links are now colored correctly. 🎉 
> [!NOTE]
> I think the theming is great. But our themes for sure need a once-over to adjust them for accessibility. And to make sure they make sense. We could probably just choose 10 from the list that look great and remove the rest.
> fix: improved theming to messages, mentions, emoji panel, and timeline view

- src/lib/components/ChatMessage.svelte
- src/lib/components/TimelineView.svelte
This commit contains fixes for #227 
Both while sending the new message while and also while editing the already sent message following cases are handles
- When message is empty
- When message contains empty spaces
- Removing spaces When message contains hardbreaks or spaces before any text
When message will be empty it will not send message and will generate the error that "Message cannot be empty".
Please let me know if I have missed anything or need to consider any other cases. 
fixes: #227
> fix: disallow sending blank message

- .github/workflows/sdk-api-docs.yaml
The publishing path didn't match the package name.
> docs: fix API docs build in CI.

- packages/sdk/src/index.ts
Adds a change that was lost in a rebase and should have come with the recent sync protocol update.
This makes sure that if the user's catalog doesn't exist yet it will be created automatically after 4 seconds of trying to load it.
Thankfully a user chatted me on Bluesky and mentioned that it just kept loading forever. Glad we caught that before the conference. :sweat_smile:
> fix: fix infinite loading spinner for new users.

- packages/app/src/lib/global.svelte.ts
Removes the instantiation of a "dummy" roomy instance before we have a valid user session. This is a bad practice and causes extra problems.
This was another fix lost in the protocol update rebase.
> fix: fix spaces disappearing soon after opening app.

- packages/sdk/src/index.ts
Not sure how it happened but some entities ended up with their IDs referenced, but their data not pushed to the syncserver. when you try to load these, if you don't have the data locally, it will just load forever. This adds a hack that will just create an empty entity with the ID after a 5 second timeout whenever this happens.
Not a good solution, but we have changes we'll need to make soon around this anyway, so it should smooth over most of the issues temporarily.
> fix: add a hack to prevent lost entities from loading infinitely.

- packages/sdk/src/index.ts
There was an issue where our hack for injecting function argument defaults into `peer.open()` was being applied recursively or something.
This makes sure it only hacks if it hasn't already been hacked.
> fix: fix stack size limit exceeded exceptions.

- packages/app/src/lib/components/content/thread/ChatArea.svelte
- packages/app/src/lib/queries.svelte.ts
- packages/app/src/lib/workers/backendWorker.ts
- packages/app/src/lib/workers/db/schema.sql
- packages/app/src/lib/workers/encoding.ts
- packages/app/src/lib/workers/materializer.ts
- packages/app/src/lib/workers/setupSqlite.ts
- packages/app/src/lib/workers/sqliteWorker.ts
- packages/app/src/routes/(app)/[space=hash]/[object=ulid]/+page.svelte
- packages/app/src/routes/(app)/[space=hash]/new/+page.svelte
This commit migrates entities to use IDs that, instead of always being ULIDs, are an enum that can be either:
- unknown: any string ID we don't understand
- ulid: a ULID
- hash: a 32 byte hash formatted in hex
- did: a DID, such as for a user account
This allows us to store everything as an entity using it's canonical ID as it's entity ID, greatly simplifying things throughout the codebase.
It also uses simplified functions in JS for encoding IDs `id()` and a SQL user-defined-function with the same name to format the IDs back to their string form during querying.
> refactor: unify entity IDs under a SCALE enum so that we don't have to maintain ID maps.

- .github/workflows/discord-bot.yaml
GitHub is sending an email on every merge to main that the discord bot CI didn't run. This switches it to have triggers, but set a condition so that the job doesn't run, which avoids the email.
> ci: make sure disabled CI job doesn't send email for not running.

- packages/app/src/lib/config.ts
- packages/app/src/lib/lexicons.ts
- packages/app/src/lib/workers/backendWorker.ts
- packages/app/src/lib/workers/encoding.ts
- packages/app/src/routes/(app)/new/+page.svelte
Adds a new streamSchemaVersion config that, when we need to change it, will automatically clear the local cache and load a new personal stream with that version number, so that the old stream info is preserved but the new version of the app has a clean slate instead of breaking by trying to read the old streams.
Also adds parameters to the stream specifying the kind of stream and the schema version, so that it's possible for the app to detect what version and kind of stream something is just from the stream metadata.
> feat: provide mechanism for updating stream schema version and avoiding the need to manually reset the local cache.

- packages/app/src/hooks.client.ts
Previous versions of Roomy had a service worker
in order to support offline use, but offline support was never actually implemented.
This unregisters the service worker if it happens to be installed from previous versions of Roomy so that it doesn't cause any problems, just in case.
> fix: disable the service worker if one is installed.
