muni-town/roomy

.gitignore
deno.lock
package.json
src/routes/+layout.ts
svelte.config.js

This forces the whole app to run purely client-side.

refactor: use svelte static adapter and configure whole site to prerender.

---

src/lib/schemas/types.ts
src/lib/utils.ts
src/routes/(app)/dm/+layout.svelte
src/routes/(app)/dm/[did]/+page.svelte

It works. Might want to refactor some things, I'm still learning the idiomatic way to manipulate things

notifications

---

src/lib/components/ChatArea.svelte
src/lib/components/ChatMessage.svelte
src/lib/components/ThreadRow.svelte
src/routes/(app)/+layout.svelte
src/routes/(app)/dm/+layout.svelte
src/routes/(app)/dm/[did]/+page.svelte
src/routes/(app)/space/[space]/+layout.svelte
src/routes/(app)/space/[space]/[channel]/+page.svelte

Refactors and implements a new mobile view for Spaces. DM UI is also matched to be similar.
Closes #58 
https://github.com/user-attachments/assets/2a620283-08dc-4142-8bfe-b65f9d47f43e

fix: mobile view for spaces

---

src/lib/components/ChatMessage.svelte
src/lib/schemas/types.ts
src/lib/user.svelte.ts
src/routes/(app)/space/[space]/[channel]/+page.svelte

initial stab at image uploads.

image uploads

---

src/routes/(app)/space/[space]/[channel]/+page.svelte

save people a step from having to save to hard drive.

add ability to paste image

---

src/lib/components/ChatMessage.svelte

Fixing #91 bug. To be honest, I'm not sure if this is everything to fix the bug, but it seems good (?)

fix: reply banner text bug

---

deno.lock
netlify.toml
scripts/netlify_build.sh

This fixes login errors for the netlify build and makes the preview deployments for pull requests work.

ci: include oauth client config in netlify build.

---

deno.lock
src/lib/components/AvatarImage.svelte
src/routes/(app)/+layout.svelte

I think this matches our vibe better than the previous styles, subject to review.
**after:**
**before:**

style: switch to marble placeholder avatar style.

---

deno.lock
package.json
src/lib/components/WikiEditor.svelte
src/lib/global.svelte.ts

Enable multiple wiki pages for each channel with CRUD functionality available.

feat: multiple wiki pages

---

static/oauth-client-native.json

change oauth client native urls from dev.roomy.chat to roomy.chat

fix: update oauth client native urls.

---

deno.lock
package.json
src/lib/components/ChatInput.svelte
src/lib/components/ChatMessage.svelte
src/lib/global.svelte.ts
src/routes/(app)/[[spaceIndicator=dash]]/[space=space]/+layout.svelte

Bans are "best effort" for now, like all moderation features. Roomy is still generally insecure.

feat: add the ability to ban users.

---

src/lib/components/ContextMenu.svelte
src/routes/(app)/+layout.svelte

feat: add context menu button to leave space.

---

src/routes/(app)/+layout.svelte

i feel like this is a smoother ux for identifying spaces

shorter delay on space hover

---

src/lib/components/TimelineView.svelte

leftover from when channels were actually Dms

remove image from channel

---

src/lib/tiptap/editor.ts
src/lib/urlUtils.ts

make links clickable

---

.vscode/extensions.json

Add extension recommendations for vscode users

---

src/lib/tiptap/editor.ts

add fuzzy matching for channel search

---

deno.lock
package.json
src/lib/components/SidebarSpace.svelte
src/routes/(app)/+layout.svelte
src/routes/(app)/[[spaceIndicator=dash]]/[space=space]/+layout.svelte

add ability to set image on a space

space image

---

src/service-worker.ts

Also formats and adds proper TypeScript types for the service worker.

fix: make sure service worker doesn't interfere with oauth login.

---

src/lib/components/ChatMessage.svelte

fixes inline messages that are slightly out of alignment. uses invisible avatar component. also using consistent time format

fix text alignment

---

src/app.css
src/lib/components/ChatInput.svelte
src/lib/components/ChatMessage.svelte
src/lib/components/ContextMenu.svelte
src/lib/components/Dialog.svelte
src/lib/components/SidebarSpace.svelte
src/lib/components/ThemeSelector.svelte
src/lib/components/ThreadsTab.svelte
src/lib/components/TimelineToolbar.svelte
src/lib/components/TimelineView.svelte
src/lib/components/WikiEditor.svelte
src/routes/(app)/+layout.svelte
src/routes/(app)/+page.svelte
src/routes/(app)/[[spaceIndicator=dash]]/[space=space]/+layout.svelte
src/routes/(app)/home/+page.svelte

chore: Add dz- prefix to daisyui classes

---

src/routes/(app)/+page.svelte

Removed this by accident in #187

add root +page back

---

scripts/netlify_build.sh
src/routes/(app)/+layout.svelte

chore: setup reverse proxy in Netlify for Posthog.

---

package.json
src-tauri/src/lib.rs
src-tauri/tauri.conf.json
svelte.config.js

Conditionally modifies build settings to create bundles which work with tauri

build: tauri configuration

---

deno.lock
package.json
src/extra-types.d.ts
tsconfig.json

chore: fix svelte-check errors and update leaf to latest version without TS errors.

---

src/lib/components/ServerBar.svelte

Adds and option to the log in flow to "signup with bsky.social" within roomy.chat. New atproto user completing the signup is then redirected back to roomy.chat.
closes #133

feat: account registration via bsky

---

src/lib/components/ChatMessage.svelte
src/lib/components/TimelineView.svelte

Oops, this change breaks the ability to post images. I'm going to post a fix today and get playwright up and running to catch things like this in the future.
cc @Jayoooppp just giving you a heads up that you're change will be put back in as soon as I fix the image issue. Having a test should have caught this one so don't feel bad!

Revert "fix: disallow sending blank message"

---

packages/app/src/lib/components/ChatInput.svelte
packages/app/src/lib/components/ChatMessage.svelte
packages/app/src/lib/components/CreatePageDialog.svelte
packages/app/src/lib/components/PageEditor.svelte
packages/app/src/lib/components/ServerBar.svelte
packages/app/src/lib/components/SidebarBoard.svelte
packages/app/src/lib/components/SidebarChannelList.svelte
packages/app/src/lib/components/SidebarMain.svelte
packages/app/src/lib/components/SidebarSpace.svelte
packages/app/src/lib/components/SpaceSettingsDialog.svelte
packages/app/src/lib/components/TimelineToolbar.svelte
packages/app/src/lib/components/TimelineView.svelte
packages/app/src/lib/global.svelte.ts
packages/app/src/routes/(app)/+layout.svelte
packages/app/src/routes/(app)/[[spaceIndicator=dash]]/[space=space]/+layout.svelte
packages/app/src/routes/(app)/[[spaceIndicator=dash]]/[space=space]/+page.svelte
packages/app/src/routes/(app)/[[spaceIndicator=dash]]/[space=space]/page/[page]/+page.svelte
packages/app/src/routes/(app)/home/+page.svelte

Sorry, I couldn't do the whole one-letter variable anymore. 😉
Verbosity over fewer characters every time in my book.

chore: replaces g with globalState

---

packages/app/src/lib/components/ThemeSelector.svelte
packages/app/src/lib/utils.svelte.ts
packages/app/src/routes/(app)/+layout.svelte

Removed this by accident last time. So I refactored it to make it cleaner.

fix: mobile theme change

---

package.json
packages/app/.env.example
packages/app/package.json
packages/app/src/lib/components/ServerBar.svelte
packages/app/src/lib/components/ThemeSelector.svelte
packages/app/src/lib/profile.svelte.ts
packages/app/src/routes/(app)/discord-import/+page.svelte
packages/sdk/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

feat: expose first draft of Discord import in dev.

---

README.md

pnpm run build no longer needed for dev

---

packages/app/src/app.css
packages/app/src/lib/components/SearchResults.svelte
packages/app/src/lib/components/TimelineView.svelte

This was suppose to be in #267 and I left it out.

Adjusts size of images in replies

---

packages/app/src/lib/components/LinkCard.svelte
packages/app/src/lib/types/embed-sdk.d.ts
packages/app/src/lib/utils/getLinkEmbedData.ts

feat: link previews

---

.github/workflows/release-tauri.yml
packages/app/src-tauri/gen/android/buildSrc/src/main/java/chat/roomy/app/kotlin/BuildTask.kt

remove conflicting pnpm version between workflow and package.json
run tauri commands with pnpm
update  source icon location
generate web app in CI
build libs before app

fix: tauri ci updates

---

packages/app/src/lib/components/ChatMessage.svelte
packages/app/src/lib/components/Message/MessageReactions.svelte

lists who reacted to message on emoji hover

list reaction users on hover

---

packages/app/src/lib/components/ChatArea.svelte

quickly jump to present if scrolled away from bottom

jump to present

---

packages/app/src/lib/components/ChatArea.svelte

kinda hacky but it works until we find something better

scroll to bottom on load

---

packages/app/vite.config.ts

hack for my system and [and potentially others like mine]

add path to vite allowed

---

.github/workflows/sdk-api-docs.yaml
packages/app/package.json
packages/app/svelte.config.js
pnpm-lock.yaml
pnpm-workspace.yaml
scripts/netlify_build.sh

Fixes Netlify preview deployments for pull requests.

ci: configure Netlify to work for PR preview builds.

---

packages/app/src/lib/components/layout/Navbar.svelte

feat: add "About Roomy" link to the header.

---

packages/app/src/lib/workers/materializer.ts

Fixes a bug where we were re-fetching the Bluesky profile every single time a message was sent.

fix: fix extraneous profile fetches.
